spring:
  # 配置数据库信息
  datasource:
    # 数据源配置
    username: spring
    password: spring
    url: jdbc:mysql://127.0.0.1:3306/spring
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource   # 指定数据源为druid
    druid:

      # 初始化 最小 最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#      aop-patterns: com.springcloud.controller.*
      # 配置多个英文逗号分隔
      filters: stat,wall

# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mapper/*Mapper.xml #mybatis的mapper文件扫描路径
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.springcloud.demo.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    # 热加载mapper文件
    refresh: true
#    pagination-interceptor: com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor #分页插件
    db-config:
      db-type: mysql
#      sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector #配置逻辑删除插件，mybatis plus 3.1.1后无需配置
      logic-delete-value: 1 #删除后的状态 默认值1
      logic-not-delete-value: 0 #逻辑前的值 默认值0

